### ISSUE TITLE
Addon doesnt work.

### ISSUE THREAD

**Issue by 22DP3BBiks** [FrederoxDev/CC-Bedrock#1]
[Scripting][error]-Plugin [CC: Bedrock] - module [CC: Bedrock - 1.0.0] requesting invalid module version [@minecraft/server-ui - 1.0.0-beta].
Available versions:
@minecraft/server-ui - 0.1.0
@minecraft/server-ui - 1.0.0
@minecraft/server-ui - 1.1.0
@minecraft/server-ui - 1.2.0-beta

[Scripting][error]-Plugin [CC: Bedrock] - module [CC: Bedrock - 1.0.0] requesting invalid module version [@minecraft/server - 1.1.0-beta].
Available versions:
@minecraft/server - 0.1.0
@minecraft/server - 1.0.0
@minecraft/server - 1.1.0
@minecraft/server - 1.2.0
@minecraft/server - 1.3.0
@minecraft/server - 1.4.0
@minecraft/server - 1.5.0
@minecraft/server - 1.6.0
@minecraft/server - 1.7.0
@minecraft/server - 1.8.0-beta

[Scripting][error]-Plugin [CC: Bedrock] - version conflict for [@minecraft/server] - [CC: Bedrock - 1.0.0] requested [@minecraft/server - 1.1.0-beta] but [@minecraft/server-gametest - 1.0.0-beta] requested [@minecraft/server - 1.8.0-beta]

**Comment by FrederoxDev** [comment]
I'm grateful that you made an issue for CC-Bedrock, but i never finished the project 😅 nor really do I plan at the moment to come back to it

I suspect the issue is because I was using the latest versions of scripting at the time, which are by now very outdated

Also I'm kind of surprised that you compiled the add-on? Did you go through my compiler (Astra) to do that, just curious?

**Comment by 22DP3BBiks** [comment]
1) No, I used the release, but i did see that astra thing you made.
2) Yes, it is to do with the version and i tried fixing it, but it lead to code not working and i can assume there has been a lot of changes since that version.

**Comment by 22DP3BBiks** [comment]
Would have it changed anything if i used the compiled version?

**Comment by FrederoxDev** [comment]
Ah okay, yeah I would guess there would've been some breaking changes in the scripting APIs since. 

The main code for the interpreted language will still be working fine, it's just how it interacts with Minecraft that'll be broken

**Comment by FrederoxDev** [comment]
> Would have it changed anything if i used the compiled version?

Nah, you would have to update the code and the BP manifest.json file to use a more recent version of scripting

**Comment by 22DP3BBiks** [comment]
![image](https://github.com/FrederoxDev/CC-Bedrock/assets/103173909/00a977ac-7f74-4c00-8a3a-f37377419d18)
What? Where can i find all commands?

**Comment by FrederoxDev** [comment]
https://github.com/FrederoxDev/CC-Bedrock/blob/master/BP/scripts/main.ts#L55-L164

**Comment by 22DP3BBiks** [comment]
Huh, turn out help command didnt have any logic.

**Comment by FrederoxDev** [comment]
Like I said at the start, unfinished project. Even the programming language itself isn't complete yet, still needs to have member variables for classes to be implemented and probably a lot more

**Comment by 22DP3BBiks** [comment]
Does your Cosmic have print function or any other form of output beside display?
